package com.flattery;

import com.flattery.models.Favorite;
import com.flattery.repositories.FavoriteRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path = "/favorite")

public class FavoriteController {
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    FavoriteRepository favoriteRepository;

    public FavoriteController(FavoriteRepository favoriteRepository)
    {
        this.favoriteRepository = favoriteRepository;
    }


    @GetMapping(path = "/add")
    public @ResponseBody
    String addFavorite(@RequestParam Integer User_id, @RequestParam Integer Wohnung_id) {

        Favorite favorite = new Favorite();
        favorite.setUser_id(User_id);
        favorite.setWohnung_id(Wohnung_id);

        favoriteRepository.save(favorite);

        return "Success";
    }

    @GetMapping(path = "/remove")
    public @ResponseBody
    String removeFavorite(@RequestParam Integer id) {

        try {
            Favorite favorite = new Favorite();
            favoriteRepository.delete(favorite);

        } catch (IllegalArgumentException exc) {

            return "Failed";
        }

        return "Success";
    }

    @GetMapping(path = "/clear")
    public @ResponseBody
    String clearFavorites() {

        favoriteRepository.deleteAll();

        return "Success";
    }

}
